language: android
dist: trusty
android:
  components:
    - android-29
    - build-tools-29.0.2

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - chmod +x gradlew
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

script:
  - ./gradlew clean :cieloecommerceoauth:assembleDebug :cieloecommerceoauth:assembleRelease

# deploy section
deploy:
  provider: script
  script: ./gradlew :cieloecommerceoauth:bintrayUpload
  on:
    branch: master
